import { Router } from 'express';
import userRouter from './userRouter.router';
import productRouter from './productRouter.router';
import categoryRouter from './categoryRouter.router';
import employeeRouter from './employeeRouter.router';
import brandRouter from './brandRouter.router';
import branchRouter from './branchRouter.router';
import branchProductRouter from './branchProductRouter.router';
import branchUserRouter from './branchUserRouter.router';
import invoiceRouter from './invoiceRouter.router';
import menuRouter from './menuRouter.router';
import menuCategoryRouter from './menuCategoryRouter.router';
import invoiceDetailRouter from './invoiceDetailRouter.router';
import branchMenuRouter from './branchMenuRouter.router';
import transferProductRouter from './transferProductRouter.router';
import stockAdjustmentRouter from './stockAdjustmentRouter.router';
import supplierRouter from './supplierRouter.router';
import stockAdjustment_detailRouter from './stockAdjustment_detailRouter.router';
import transfer_detailRouter from './transferDetailRouter.router';
import tableRouter from './tableRouter.router';
import orderStatusRouter from './orderStatusRouter.router';
import orderRouter from './orderRouter.router';
import orderDetailRouter from './orderDetailRouter.router';
import tableOrderRouter from './tableOrderRouter.router';
import purchaseOrderRouter from './Purchase_orderRouter.router';
import purchaseOrderDetailRouter from './purchase_order_detailRouter.router';
import tableStatusRouter from './tableStatusRouter.router';

const routes = Router();

routes.use('/api/users', userRouter);
routes.use('/api/product', productRouter);
routes.use('/api/category', categoryRouter);
routes.use('/api/employee', employeeRouter);
routes.use('/api/brand', brandRouter);
routes.use('/api/branch', branchRouter);
routes.use('/api/branchProduct', branchProductRouter);
routes.use('/api/branch_user', branchUserRouter);
routes.use('/api/invoice', invoiceRouter);
routes.use('/api/menu', menuRouter);
routes.use('/api/menuCategory', menuCategoryRouter);
routes.use('/api/branchMenu', branchMenuRouter);
routes.use('/api/invoiceDetail', invoiceDetailRouter);
routes.use('/api/transferProduct', transferProductRouter);
routes.use('/api/stockAdjustment', stockAdjustmentRouter);
routes.use('/api/supplier', supplierRouter);
routes.use('/api/stockAdjustment_detail', stockAdjustment_detailRouter);
routes.use('/api/transfer_detail', transfer_detailRouter);
routes.use('/api/table', tableRouter);
routes.use('/api/orderStatus', orderStatusRouter);
routes.use('/api/order', orderRouter);
routes.use('/api/orderDetail', orderDetailRouter);
routes.use('/api/tableOrder', tableOrderRouter);
routes.use('/api/tableStatus', tableStatusRouter);
routes.use('/api/purchaseOrder', purchaseOrderRouter);
routes.use('/api/purchaseOrderDetail', purchaseOrderDetailRouter);

export default routes;